### ISSUE TITLE
0.7.0 GUI increased latency showing reload icon after clicking on multi-image captchas

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/librecaptcha#10]
With 0.7.0, the GUI version of librecaptcha seems to have increased the latency of the reload icon appearing (and the verify button being disabled) on the multi-image captchas from approximately instantly to something like 0.75 seconds.

In addition, during the 0.75 seconds, any existing reload icons have their animations stopped.

**Comment by taylordotfish** [comment]
Fixed in 0.7.1.
