### ISSUE TITLE
0.7.1 GUI has freezes of the reload icon animation with multi-image captcha

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/librecaptcha#13]
The latency has been fixed, but in the 0.7.1 GUI mode, when I rapidly click all of the images in a multi-image captcha, some of the reload icon animations will be paused (but most won't). It is also possible to hit this without clicking everything madly but much rarer. The paused animations in either case do not happen with 0.6.5 though.

**Comment by taylordotfish** [comment]
Yeah, I noticed this, but I really have no idea why it's happening. I generally don't like to jump to blaming other pieces of software, but I think it might be a bug in GTK.

One thing I noticed about this is that when one of the animations freezes, if you unfocus the window, it'll start playing again and will continue to play when the window is refocused.

If you or anyone else has any ideas about why this might be happening, please feel free to comment on this issue or open a PR.

**Comment by taylordotfish** [comment]
Fixed (I think) in version 0.7.2. (In my defense, it kind of *is* a bug in GTK—the spinner has to be added to a container before it's started to avoid this issue, which shouldn't be the case IMO.)

**Comment by pabs3** [comment]
Confirmed that it is fixed, thanks.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
